# Generated by Django 5.2.8 on 2025-11-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_description',
        ),
    ]
